name: Build and Deploy
on: 
  push:
    branches:
      - master

jobs:
  build:
    name: Gatsby Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: yarn install
      - uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - run: |
          git config --global user.email 'github-action@users.noreply.github.com'
          git config --global user.name 'RustFest Website deploy'
          git remote set-url origin https://badboy:${{ secrets.GITHUB_TOKEN }}@github.com/${{ env:GITHUB_REPOSITORY }}
          yarn deploy
